// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ-Bf-IiTgVrbC-eFL2tWEKp-6EoCWDt0',
    appId: '1:253442567784:web:7fbde2cc1000a4825995dd',
    messagingSenderId: '253442567784',
    projectId: 'piet-bus-tracker-b3804',
    authDomain: 'piet-bus-tracker-b3804.firebaseapp.com',
    storageBucket: 'piet-bus-tracker-b3804.appspot.com',
    measurementId: 'G-0923D5BF13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfbUGlXnEII_ipmrJwX9O-D1-qAs3lUBg',
    appId: '1:253442567784:android:95d3b51d212476c35995dd',
    messagingSenderId: '253442567784',
    projectId: 'piet-bus-tracker-b3804',
    storageBucket: 'piet-bus-tracker-b3804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkOYULG_Jl_BsMhb3fuGGPgx9dkIG-NGs',
    appId: '1:253442567784:ios:b6177012aeb5770b5995dd',
    messagingSenderId: '253442567784',
    projectId: 'piet-bus-tracker-b3804',
    storageBucket: 'piet-bus-tracker-b3804.appspot.com',
    iosBundleId: 'in.co.piet.liveLocationChecker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkOYULG_Jl_BsMhb3fuGGPgx9dkIG-NGs',
    appId: '1:253442567784:ios:548e1f0c7a7874b85995dd',
    messagingSenderId: '253442567784',
    projectId: 'piet-bus-tracker-b3804',
    storageBucket: 'piet-bus-tracker-b3804.appspot.com',
    iosBundleId: 'in.co.piet.liveLocationChecker.RunnerTests',
  );
}
